global using System;
global using Xunit;
global using FluentAssertions;
global using matchmaking.Domain.Enums;
global using matchmaking.Domain.Entities;
global using matchmaking.Converters;
global using matchmaking.Views.Converters;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Media;
